name: process pull request

on:
  workflow_run:
    workflows: [build pull request]
    types: [completed]

jobs:
  process-pr:
    runs-on: ubuntu-latest
    name: Process pull request
    steps:
      - name: Process pull request
        uses: MilesCranmer/showyourwork-action/process-pull-request@latexdiff
